# Simple workflow for deploying static content to GitHub Pages
name: Deploy sonolus generated static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["testserver"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: testserver
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Run sonolus static generator
        run: |
          mkdir static
          npx sonolus-generate-static@4.0.1 -i gfriend/pack -o static/gfriend
          npx sonolus-generate-static@4.0.1 -i loona/pack -o static/loona
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: static/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload contents of static
          path: 'static/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
